### ISSUE TITLE
" rank_zero_only " runtime error

### ISSUE THREAD

**Issue by ctankep** [deforum-art/deforum-stable-diffusion#1]
Running `Deforum_Stable_Diffusion.py` :
Though can't find " rank_zero_only " from `pytorch.lightning.utilities.distributed`. This gets imported from `ddpm.py` but works without running that logging command. Which seems to have been added as a work around for crashes during longer training sessions in this issue :
[[ https://github.com/Lightning-AI/lightning/issues/8821 ]](https://github.com/Lightning-AI/lightning/issues/8821)

**Comment by ctankep** [comment]
Installed versions :
![image](https://user-images.githubusercontent.com/129326/199254056-6661826f-e4bd-4d3e-9282-1e709bfc3525.png)

**Comment by ctankep** [comment]
Installed versions :
![image](https://user-images.githubusercontent.com/129326/199254241-bbd8b155-aeca-4c08-9a61-a6d6001604c8.png)

**Comment by ctankep** [comment]
![image](https://user-images.githubusercontent.com/129326/199254793-c90c7d15-5f76-4daa-9191-75bb9548ff1b.png)

**Comment by ctankep** [comment]
Runs ok disabling " rank_zero_only "

**Comment by deforum** [comment]
ah i see changing the version of pytorch lightning to 1.7.7 works

**Comment by deforum** [comment]
gonna update the repo
