### ISSUE TITLE
It cant make animations using a 1.5 custom model (dreamlike-diffusion)

### ISSUE THREAD

**Issue by davvoz** [deforum-art/deforum-stable-diffusion#100]
From last release 
2D animation prints an image next exit whit this error

`AttributeError                            Traceback (most recent call last)
[<ipython-input-19-942f4e77eec3>](https://localhost:8080/#) in <module>
    153 # dispatch to appropriate renderer
    154 if anim_args.animation_mode == '2D' or anim_args.animation_mode == '3D':
--> 155     render_animation(args, anim_args, animation_prompts, root)
    156 elif anim_args.animation_mode == 'Video Input':
    157     render_input_video(args, anim_args, animation_prompts, root)

[/content/deforum-stable-diffusion/helpers/render.py](https://localhost:8080/#) in render_animation(args, anim_args, animation_prompts, root)
    406             # use transformed previous frame as init for current
    407             args.use_init = True
--> 408             if root.half_precision:
    409                 args.init_sample = noised_sample.half().to(root.device)
    410             else:

AttributeError: 'types.SimpleNamespace' object has no attribute 'half_precision'`

3D animation  same error and prints nothing.
Interpolation works

**Comment by deforum** [comment]
should be fixed now
