### ISSUE TITLE
log_weighted_subprompts issue

### ISSUE THREAD

**Issue by FloLey** [deforum-art/deforum-stable-diffusion#105]
On the latest colab notebook, whenever I use "log_weighted_subprompts" I get this error: AttributeError: 'FrozenOpenCLIPEmbedder' object has no attribute 'tokenizer'.
Thanks in advance

**Comment by dcsan** [comment]
thanks for pointing this out as a workaround disabling:  `log_weighted_subprompts`
thats why only some people in the discord (me included) were having the issue.

**Comment by deforum** [comment]
no plans to fix this issue for the time being
