### ISSUE TITLE
xformers error on install 

### ISSUE THREAD

**Issue by prismspecs** [deforum-art/deforum-stable-diffusion#116]
`..installing git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [242 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/xformers
      copying xformers/version.py -> build/lib.linux-x86_64-cpython-310/xformers
      copying xformers/utils.py -> build/lib.linux-x86_64-cpython-310/xformers
      copying xformers/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers
      copying xformers/info.py -> build/lib.linux-x86_64-cpython-310/xformers
      copying xformers/test.py -> build/lib.linux-x86_64-cpython-310/xformers
      copying xformers/_cpp_lib.py -> build/lib.linux-x86_64-cpython-310/xformers
      creating build/lib.linux-x86_64-cpython-310/xformers/helpers
      copying xformers/helpers/hierarchical_configs.py -> build/lib.linux-x86_64-cpython-310/xformers/helpers
      copying xformers/helpers/timm_sparse_attention.py -> build/lib.linux-x86_64-cpython-310/xformers/helpers
      copying xformers/helpers/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/helpers
      copying xformers/helpers/test_utils.py -> build/lib.linux-x86_64-cpython-310/xformers/helpers
      creating build/lib.linux-x86_64-cpython-310/xformers/ops
      copying xformers/ops/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
      copying xformers/ops/swiglu_op.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
      copying xformers/ops/unbind.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
      copying xformers/ops/common.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
      creating build/lib.linux-x86_64-cpython-310/xformers/sparse
      copying xformers/sparse/utils.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
      copying xformers/sparse/csr_tensor.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
      copying xformers/sparse/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
      copying xformers/sparse/blocksparse_tensor.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
      copying xformers/sparse/_csr_ops.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
      creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/flash_blocksparse_attention.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/flash_attn_triton.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/flash_attention.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/bert_padding.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/flash_attn_interface.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/flash_attn_triton_og.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/flash_blocksparse_attn_interface.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      copying xformers/_flash_attn/fused_softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
      creating build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/dropout.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/utils.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/layer_norm.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/sum_strided.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/k_sum.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/k_dropout.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/fused_linear_layer.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/k_layer_norm.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/k_fused_matmul_fw.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/k_fused_matmul_bw.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/k_softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      copying xformers/triton/k_activations.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
      creating build/lib.linux-x86_64-cpython-310/xformers/components
      copying xformers/components/input_projection.py -> build/lib.linux-x86_64-cpython-310/xformers/components
      copying xformers/components/reversible.py -> build/lib.linux-x86_64-cpython-310/xformers/components
      copying xformers/components/simplicial_embedding.py -> build/lib.linux-x86_64-cpython-310/xformers/components
      copying xformers/components/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/components
      copying xformers/components/multi_head_dispatch.py -> build/lib.linux-x86_64-cpython-310/xformers/components
      copying xformers/components/residual.py -> build/lib.linux-x86_64-cpython-310/xformers/components
      copying xformers/components/activations.py -> build/lib.linux-x86_64-cpython-310/xformers/components
      copying xformers/components/patch_embedding.py -> build/lib.linux-x86_64-cpython-310/xformers/components
      creating build/lib.linux-x86_64-cpython-310/xformers/factory
      copying xformers/factory/model_factory.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
      copying xformers/factory/block_factory.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
      copying xformers/factory/weight_init.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
      copying xformers/factory/block_configs.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
      copying xformers/factory/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
      copying xformers/factory/hydra_helper.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
      creating build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_causal_blocksparse.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_vit_timm.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_triton_fused_linear.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_triton_dropout.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_transformer.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_revnet.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_pytorch_transformer.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_nystrom_utils.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_core.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/utils.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_triton_layernorm.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_multi_head_dispatch.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_encoder.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_triton_stride_sum.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_nvfuser.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_blocksparse_transformers.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_triton_blocksparse.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_sddmm.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_triton_softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_mem_eff_attention.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      copying xformers/benchmarks/benchmark_swiglu.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
      creating build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      copying xformers/ops/fmha/triton.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      copying xformers/ops/fmha/tensor_with_seqlen.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      copying xformers/ops/fmha/flash.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      copying xformers/ops/fmha/small_k.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      copying xformers/ops/fmha/cutlass.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      copying xformers/ops/fmha/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      copying xformers/ops/fmha/dispatch.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      copying xformers/ops/fmha/common.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
      creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/losses
      copying xformers/_flash_attn/losses/cross_entropy.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/losses
      copying xformers/_flash_attn/losses/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/losses
      creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
      copying xformers/_flash_attn/utils/distributed.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
      copying xformers/_flash_attn/utils/generation.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
      copying xformers/_flash_attn/utils/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
      copying xformers/_flash_attn/utils/pretrained.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
      copying xformers/_flash_attn/utils/benchmark.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
      creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
      copying xformers/_flash_attn/ops/gelu_activation.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
      copying xformers/_flash_attn/ops/layer_norm.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
      copying xformers/_flash_attn/ops/fused_dense.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
      copying xformers/_flash_attn/ops/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
      creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/layers
      copying xformers/_flash_attn/layers/rotary.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/layers
      copying xformers/_flash_attn/layers/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/layers
      copying xformers/_flash_attn/layers/patch_embed.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/layers
      creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
      copying xformers/_flash_attn/models/bert.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
      copying xformers/_flash_attn/models/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
      copying xformers/_flash_attn/models/gpt.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
      copying xformers/_flash_attn/models/vit.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
      creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
      copying xformers/_flash_attn/modules/mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
      copying xformers/_flash_attn/modules/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
      copying xformers/_flash_attn/modules/embedding.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
      copying xformers/_flash_attn/modules/block.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
      copying xformers/_flash_attn/modules/mha.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
      creating build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
      copying xformers/components/feedforward/mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
      copying xformers/components/feedforward/base.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
      copying xformers/components/feedforward/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
      copying xformers/components/feedforward/conv_mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
      copying xformers/components/feedforward/mixture_of_experts.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
      copying xformers/components/feedforward/fused_mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
      creating build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
      copying xformers/components/positional_embedding/sine.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
      copying xformers/components/positional_embedding/base.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
      copying xformers/components/positional_embedding/rotary.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
      copying xformers/components/positional_embedding/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
      copying xformers/components/positional_embedding/vocab.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
      copying xformers/components/positional_embedding/param.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
      creating build/lib.linux-x86_64-cpython-310/xformers/components/nvfuser
      copying xformers/components/nvfuser/bias_dropout_res.py -> build/lib.linux-x86_64-cpython-310/xformers/components/nvfuser
      copying xformers/components/nvfuser/bias_dropout_res_layernorm.py -> build/lib.linux-x86_64-cpython-310/xformers/components/nvfuser
      copying xformers/components/nvfuser/utils.py -> build/lib.linux-x86_64-cpython-310/xformers/components/nvfuser
      copying xformers/components/nvfuser/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/components/nvfuser
      copying xformers/components/nvfuser/bias_act_dropout.py -> build/lib.linux-x86_64-cpython-310/xformers/components/nvfuser
      creating build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/compositional.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/fourier_mix.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/base.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/pooling.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/blocksparse.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/utils.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/attention_patterns.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/attention_mask.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/core.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/visual.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/lambda_layer.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/scaled_dot_product.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/favor.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/global_tokens.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/linformer.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/ortho.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/_sputnik_sparse.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/random.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/local.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/nystrom.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      copying xformers/components/attention/sparsity_config.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
      creating build/lib.linux-x86_64-cpython-310/xformers/components/attention/feature_maps
      copying xformers/components/attention/feature_maps/softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention/feature_maps
      copying xformers/components/attention/feature_maps/base.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention/feature_maps
      copying xformers/components/attention/feature_maps/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention/feature_maps
      creating build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
      copying xformers/benchmarks/LRA/run_with_submitit.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
      copying xformers/benchmarks/LRA/run_grid_search.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
      copying xformers/benchmarks/LRA/batch_fetch_results.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
      copying xformers/benchmarks/LRA/run_tasks.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
      copying xformers/benchmarks/LRA/batch_submit.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
      copying xformers/benchmarks/LRA/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
      creating build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA/code
      copying xformers/benchmarks/LRA/code/dataset.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA/code
      copying xformers/benchmarks/LRA/code/model_wrapper.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA/code
      copying xformers/benchmarks/LRA/code/__init__.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA/code
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-thokedub/xformers_aa405b3b9c954c6287e9afdef23a714a/setup.py", line 363, in <module>
          setuptools.setup(
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-thokedub/xformers_aa405b3b9c954c6287e9afdef23a714a/setup.py", line 308, in build_extensions
          super().build_extensions()
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 485, in build_extensions
          compiler_name, compiler_version = self._check_abi()
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 869, in _check_abi
          _, version = get_compiler_abi_compatibility_and_version(compiler)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 336, in get_compiler_abi_compatibility_and_version
          if not check_compiler_ok_for_platform(compiler):
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 290, in check_compiler_ok_for_platform
          which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/grayson/miniconda3/envs/dsd/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  error: subprocess-exited-with-error
`

**Comment by deforum** [comment]
fixed
