### ISSUE TITLE
DDIM broken after first frame [latest updated notebook]

### ISSUE THREAD

**Issue by immx2** [deforum-art/deforum-stable-diffusion#122]
First 3 frames below, settings attached.

![20230115015205_00000](https://user-images.githubusercontent.com/53500318/212519392-4f8c9d44-29dc-467c-8b1f-eb8a7f4e80eb.png)
![20230115015205_00001](https://user-images.githubusercontent.com/53500318/212519418-54ad8416-8661-4aac-9236-03588f967494.png)
![20230115015205_00002](https://user-images.githubusercontent.com/53500318/212519423-633e98fb-228a-44a7-94ed-bd98066f5837.png)
[20230115015205_settings.txt](https://github.com/deforum-art/deforum-stable-diffusion/files/10419327/20230115015205_settings.txt)

**Comment by deforum** [comment]
hi there thank checking this out

**Comment by deforum** [comment]
fixed, will see updated code in dev shortly
