### ISSUE TITLE
Masks not working with ddim

### ISSUE THREAD

**Issue by S4f3tyMarc** [deforum-art/deforum-stable-diffusion#126]
this error comes up when trying to use a mask with ddim  main  works fine in dev 

 IndexError                                Traceback (most recent call last)
[<ipython-input-12-2feb56b213e0>](https://localhost:8080/#) in <module>
    159     render_interpolation(args, anim_args, animation_prompts, root)
    160 else:
--> 161     render_image_batch(args, prompts, root)

6 frames
[/content/deforum-stable-diffusion/helpers/callback.py](https://localhost:8080/#) in img_callback_(self, img, pred_x0, i)
    117             i_inv = len(self.sigmas) - i - 1
    118             init_noise = self.sampler.stochastic_encode(self.init_latent, torch.tensor([i_inv]*self.batch_size).to(self.device), noise=self.noise)
--> 119             is_masked = torch.logical_and(self.mask >= self.mask_schedule[i], self.mask != 0 )
    120             new_img = init_noise * torch.where(is_masked,1,0) + img * torch.where(is_masked,0,1)
    121             img.copy_(new_img)

IndexError: index 46 is out of bounds for dimension 0 with size 46

**Comment by deforum** [comment]
if dev works fine then this is not an issue, will sync dev with main soon
