### ISSUE TITLE
TPU, flax support

### ISSUE THREAD

**Issue by tralala87** [deforum-art/deforum-stable-diffusion#139]
Hi.

Would it be perhaps possible to modify the https://github.com/deforum-art/deforum-stable-diffusion/blob/main/Deforum_Stable_Diffusion.ipynb
for Flax and TPU?

Trying my best, but no success so far :)

**Comment by deforum** [comment]
i am not a flax/tpu expert, if you figure out how to modify the codebase that would be a useful contribution
