### ISSUE TITLE
Neither dev nor ffmpeg notebooks running at all after yesterday's update

### ISSUE THREAD

**Issue by AlekseyCalvin** [deforum-art/deforum-stable-diffusion#146]
The dev notebook was working for me up until last evening (Pacific Time). Since then I've spent hours unsuccessfully trying to get it to work, iteratively testing few dozen different parameter changes using several 1.x-based models, while hoping it was just a minor notebook-level code jam or parameter conflict. So, to confirm that the issue wasn't related to my settings, I've tried to first launch from the same parameters that worked for me earlier the same day (fail), then from a generic settings file (fail), and finally to launch both notebooks in near-"default" states using an entirely different Google/Drive/Colab account from my usuals (another fail, times a few). I guess I haven't yet tried different configs, though I doubt the mismatch is there. Ditto for 2.x-based models. I haven't tested to see whether or not the 'main' notebook still runs, but by now the idea of reverting to any version of Deforum notebook with no half-reliable unconditional prompting seems no less depressing than functionality somehow imploding altogether. 

Now, below this paragraph I've pasted the error printed after every on-going launch fail. Evidently, this error is tied to the hybrid video compositing feature set which,  never fully worked for me in the first place, despite many every-which-way attempts to get them to work as advertised. I'm aware of the dedicated hybrid comp guide doc, and would consult it from the start, to no avail. For me, the only working element of the hybrid video feature has been the video flow/motion matching, which would successfully work with all other hybrid settings off; albeit, with its utility severely limited by a lack of working frame comp/blending or, for that matter, any form of video input whatsoever, ever since the recent dev notebook updates (stellar in many other ways!). In trying to get hybrid comp working, I've already tried extracting frames in advance, and have tried just about everything else I could think of or have read about in posts on Discord or here. But maybe I missed something. In any case, I could detail my experience with hybrid/video errors in a separate post, once this current issue gets resolved and I'm able to access any notebook with uncond prompting at all... Now, despite all my endless setup experiments and tinkering attempts, I do still wonder if I'm simply neglecting or missing something "obvious", some key setup detail, or am fumbling some sequence of prerequisite actions at some stage, whether in respect to the current global launch fails or to the more isolated issue of non-working hybrid comp features. I really don't know. And so, now, at last, I'm doing what I should've probably done in the first place: that is, reporting my experience with these issues and appealing for help.
>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-10-2d3470378a3e>](https://localhost:8080/#) in <module>
    150 # dispatch to appropriate renderer
    151 if anim_args.animation_mode == '2D' or anim_args.animation_mode == '3D':
--> 152     render_animation(root, anim_args, args, cond_prompts, uncond_prompts)
    153 elif anim_args.animation_mode == 'Video Input':
    154     render_input_video(root, anim_args, args, cond_prompts, uncond_prompts)

[/content/deforum-stable-diffusion/helpers/render.py](https://localhost:8080/#) in render_animation(root, anim_args, args, cond_prompts, uncond_prompts)
    192     # handle hybrid video generation
    193     if anim_args.animation_mode in ['2D','3D']:
--> 194         if anim_args.hybrid_composite or anim_args.hybrid_motion in ['Affine', 'Perspective', 'Optical Flow']:
    195             args, anim_args, inputfiles = hybrid_generation(args, anim_args, root)
    196             # path required by hybrid functions, even if hybrid_comp_save_extra_frames is False

AttributeError: 'types.SimpleNamespace' object has no attribute 'hybrid_composite'

**Comment by amalpushp77** [comment]
Similar error after today's update

AttributeError: 'types.SimpleNamespace' object has no attribute 'legacy_colormatch'
