### ISSUE TITLE
Negative prompts 

### ISSUE THREAD

**Issue by tralala87** [deforum-art/deforum-stable-diffusion#151]
Hi again :)
How can one add negative prompts to animation_prompts?

**Comment by AbdulRehman555** [comment]
You can add negative prompts by specifying the weightage for keywords/phrases. For example:
`animation_prompt = "portrait of Tom Cruise with serious face, 1: Ugly Face:-1"
`
In the example above, we are assigning weightage of -1 to the words (characteristics we don't want to be part of our generated image) and assigning positive 1 to characteristics we want.

**Comment by tralala87** [comment]
Thank you very much!

**Comment by deforum** [comment]
this is prompt weighting which is different than negative prompting, negative prompts are supported in the dev branch

**Comment by tralala87** [comment]
> animation_prompt = "portrait of Tom Cruise with serious face, 1: Ugly Face:-1"

Did you mean `animation_prompt = "portrait of Tom Cruise with serious face:1, Ugly Face:-1" ` ??
