### ISSUE TITLE
Download Issues

### ISSUE THREAD

**Issue by Steppr** [deforum-art/deforum-stable-diffusion#161]
I wanted to play with deforum and started it for the first time. It was about to download AdaBins_nyu.pt but failed to do so. The download stagnated and failed. 
Appearently if the download fails there will be a currupted file in the models directory and deforum will try to use that . That is not ideal. 
Not sure if it would have fixed itself after restarting cause i fixed it when i saw it trying to use the corrupt download.

**Comment by deforum** [comment]
we can add a checksum

**Comment by deforum** [comment]
and redownload if needed
