### ISSUE TITLE
New User - Jupyter-Lab gives error when rendering the third image

### ISSUE THREAD

**Issue by ruvidan** [deforum-art/deforum-stable-diffusion#170]
It will make two png files and then it errors out.   Any ideas what I should be looking for?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 155
    153 # dispatch to appropriate renderer
    154 if anim_args.animation_mode == '2D' or anim_args.animation_mode == '3D':
--> 155     render_animation(args, anim_args, animation_prompts, root)
    156 elif anim_args.animation_mode == 'Video Input':
    157     render_input_video(args, anim_args, animation_prompts, root)

File D:\Dropbox\Projection\AI\deforum-stable-diffusion\helpers\render.py:387, in render_animation(args, anim_args, animation_prompts, root)
    385         color_match_sample = prev_img.copy()
    386     else:
--> 387         prev_img = maintain_colors(prev_img, color_match_sample, anim_args.color_coherence)
    389 # apply scaling
    390 contrast_sample = prev_img * contrast

File D:\Dropbox\Projection\AI\deforum-stable-diffusion\helpers\colors.py:15, in maintain_colors(prev_img, color_match_sample, mode)
     13 prev_img_lab = cv2.cvtColor(prev_img, cv2.COLOR_RGB2LAB)
     14 color_match_lab = cv2.cvtColor(color_match_sample, cv2.COLOR_RGB2LAB)
---> 15 matched_lab = match_histograms(prev_img_lab, color_match_lab, multichannel=True)
     16 return cv2.cvtColor(matched_lab, cv2.COLOR_LAB2RGB)

File C:\Anaconda\envs\dsd\lib\site-packages\skimage\_shared\utils.py:326, in channel_as_last_axis.__call__.<locals>.fixed_func(*args, **kwargs)
    323 channel_axis = kwargs.get('channel_axis', None)
    325 if channel_axis is None:
--> 326     return func(*args, **kwargs)
    328 # TODO: convert scalars to a tuple in anticipation of eventually
    329 #       supporting a tuple of channel axes. Right now, only an
    330 #       integer or a single-element tuple is supported, though.
    331 if np.isscalar(channel_axis):

TypeError: match_histograms() got an unexpected keyword argument 'multichannel'

**Comment by hithereai** [comment]
How and why do you run webui using Jupyter-Lab in the first place?

**Comment by ruvidan** [comment]
Sorry this was my bad.  My Python was outdated.

**Comment by markovivl** [comment]
@ruvidan I am experiencing similar issue. To what version did you update your Python? Mine is 3.10.11
