### ISSUE TITLE
Please add Unconditional Prompts to the Main Branch

### ISSUE THREAD

**Issue by AlekseyCalvin** [deforum-art/deforum-stable-diffusion#176]
As you know, unconditional/negative prompts have become a key attribute of just about any halfway advanced Stable Diffusion workflow. And no amount of flexibility in terms of positive/negative token values may render a useable enough replacement for accessing two prompting fields (conditional/unconditional) for the same animation keyframes, like the set-up long since in place in the dev branch. In contrast, the main branch still lacks this feature, making it comparatively unusable (especially for 2.x models). So, after months of nearly exclusively using the dev branch (and without encountering, during all that time, any obvious issues re:negative prompt field specifically), I'm confused as to why this feature has not yet been merged into the main branch, where it should properly be to maximize the public usage and benefit of the toolkit as a whole.

**Comment by deforum** [comment]
working on more prompt functionality
