### ISSUE TITLE
[bug]: ControlNet doesn't seem to do anything in 2D mode

### ISSUE THREAD

**Issue by MakingMadness** [deforum-art/deforum-stable-diffusion#179]
As others have reported, ControlNet doesn't affect diffusions. To reproduce: Enable it, select preprocessor, select model, select video, and generate. The output will be as if ControlNet was disabled.

**Comment by MakingMadness** [comment]
It generates the video frames for ControlNet but not the preprocessor outputs.

**Comment by MatissesProjects** [comment]
This appears to be loading the model everytime, and grabbing frames.
For me the preprocessor step of generating the mask frames was also skipped even though it continues to look for them
![image](https://user-images.githubusercontent.com/3753211/233516533-57b88fbf-ecd6-46f9-ad46-2f2f415b4aef.png)
![image](https://user-images.githubusercontent.com/3753211/233516669-5f191004-9c76-4f68-8f20-c7bcf7ffac0f.png)

**Comment by MakingMadness** [comment]
Oh yes, I should have mentioned, I'm on Ubuntu 22.04.1 LTS

**Comment by MakingMadness** [comment]
Posted this in the wrong repo. Woops.
