### ISSUE TITLE
Can't run more than short jobs on replicate.com

### ISSUE THREAD

**Issue by boxabirds** [deforum-art/deforum-stable-diffusion#185]
Hi there -- deforum is truly amazing. I want to use it in a tool I'm building. I'm trying to use deforum-stable-difussion on replicate.com but it times out after 30 minutes and I need to generate around 9000 hi-res frames which I think takes a few hours. 

I don't have a local computer powerful enough to run reliably. Maybe I deploy can deforum somewhere else. Do you have any recommendations on now deploy deforum as an API? Maybe the steps used on replicate.com can help? 

Thanks very much in advance.

**Comment by deforum** [comment]
hmm, this sounds like an issue with replicate. i think you'd have to rent a gpu to run deforum for your project
