### ISSUE TITLE
Doesn't work with CPUs

### ISSUE THREAD

**Issue by boxabirds** [deforum-art/deforum-stable-diffusion#189]
Hi y'all -- I've been doing a deep dive into this awesome capability and AFAICT it's fairly clear that the CPU path, particularly on Macs, has never worked. Please do correct me if I'm wrong on this, but there appears to be a handfu of bugs that result in `cuda` being chosen regardless of your selection which keep pulling the execution paths into the `cuda` route which doesn't work on Macs

For example `model_load.py` line 258: load_model_from_config() has wrong number of parameters resulting in default being `cuda`. 

I have absolutely no issue with this -- and would like to help in some way. The question is: 
1. do we want to support CPUs at all? OR
2. do we accept it's `cuda` only for now and remove the extra complexity in the code base that does these checks for `map_location` and `device` (it's unclear to me what the difference is either they seem to refer to the same thing). 

I'm fine with either: (1) is more work and (2) will simplify various parts of the code base. 

Thoughts most welcome!

**Comment by deforum** [comment]
there was very little to no mac support when i was actively developing, things may have changed... happy to get your input :)

**Comment by boxabirds** [comment]
It’s a big task I think because of the dependencies ensuring they all
support Apple Silicon. Macs, in this part of the tech world, are
unfortunately very much third class citizens.

**Comment by deforum** [comment]
i have started working on a new version that will support mac
