### ISSUE TITLE
Errors in sdwebui / Deforum when attempting to "loadallsettings" settings.txt from Batch Mode / run from settings file

### ISSUE THREAD

**Issue by likwidtek** [deforum-art/deforum-stable-diffusion#190]
I'm using sdwebui and I am aware of the batch mode / run from settings option for deforum.  I was told I can load the settings file after choosing it from "run from settings file".  The expectation is that it would load all of the values into the UI so that I can edit them and view them easier.  However there are errors when attempting to do so.

![image](https://user-images.githubusercontent.com/19313135/235235269-9df62304-b865-492b-9a02-fb8730cf453e.png)

So to be clear, I go to deforum > run> enable batch mode> locate the settings.txt file.  Then on the right I click load all settings and thats when I get those errors.  This is what I see in the console:
![image](https://user-images.githubusercontent.com/19313135/235235024-d569e5ac-3cab-4bab-97cb-68cd124e451b.png)

I was told this might happen when trying to load a much older settings file so grabbed a settings file from a known good recent run, selected the file and then clicked "load all settings" on the right and still got errors

![image](https://user-images.githubusercontent.com/19313135/235235093-d0f9c556-d828-4146-bbc5-1aa6f7df561d.png)

I've tested this on two different machines with settings files from runs that successfully ran as early as yesterday.

Deforum extension for auto1111 — version 2.3b 
python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: N/A  •  gradio: 3.23.0  •  commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)  •  checkpoint: [4199bcdd14](https://google.com/search?q=4199bcdd147e11328d5f3560301d5a7ab4ac7eeefbf49dc3eb663cb3e772b9ac)

**Comment by hithereai** [comment]
Wrong repo.
