### ISSUE TITLE
setup_environment.py redundant?

### ISSUE THREAD

**Issue by boxabirds** [deforum-art/deforum-stable-diffusion#191]
Hi -- I've looked through `setup_environment.py` and I'm fairly confident these days it can be replaced by a `requirements.txt` file. 

`requirements.txt` as read by `pip` does have a way to do platform-specific installs. E.g. here's a test `requirements.txt` file I have been testing locally (I'm not even sure we need to pin the versions on `pytorch_lightning` and `transformers`…?

A whole bunch of dependencies are only for notebooks too so they can probably be removed as well (`colab-convert`, `ipython`, `ipywidgets`, `jupyterlab`, `jupyter_http_over_ws`, `matplotlib`, the list goes on.  

```
torch
torchvision
torchaudio
clean-fid
colab-convert
einops
ftfy
ipython
ipywidgets
jsonmerge
jupyterlab
jupyter_http_over_ws
kornia
matplotlib
notebook
numexpr
omegaconf
opencv-python
pandas
pytorch_lightning==1.7.7
resize-right
scikit-image
scikit-learn
timm
torchdiffeq
transformers==4.19.2
safetensors
albumentations
more_itertools
devtools
validators
numpngw
open-clip-torch
torchsde
ninja
triton; sys_platform == 'linux'
xformers

```

**Comment by vibes24** [comment]
What does your requirement.txt look like? I am unable to figure what to include and how to have these stuff "build" properly. As I got the error "RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?"

I could not figure out how to "develop" or "build". This is frustrating.

**Comment by boxabirds** [comment]
I’ve not retested it from clean but here is my requirements.txt

https://github.com/boxabirds/deforum-stable-diffusion/blob/main/requirements.txt

I’m busy right at the moment but my plan is to
- remove all the notebook deps
- update install_requirements.py to simply call pip install with
conditional index url parameter, adding cu117 for Windows. It’d make it
just a few lines of code.

**Comment by vibes24** [comment]
Thanks but I still have no clue on how to install based on that .txt file since it's not a script.

**Comment by boxabirds** [comment]
I’ve raised a PR to fix the Windows install issue — tested locally seems to
work ok

**Comment by deforum** [comment]
setup is not redundant, it is strictly for colab users
