### ISSUE TITLE
Windows install fails

### ISSUE THREAD

**Issue by boxabirds** [deforum-art/deforum-stable-diffusion#194]
Hi I'm getting the following error on Windows

```
ERROR: Wheel 'xformers' located at C:\Users\boxab\AppData\Local\Temp\pip-unpack-2pxlb3sb\xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl is invalid.
```

I think the install scripts outside of the `ipynb` file are out of date. I'm hoping we can just use generic `requirements.txt` maybe.

**Comment by vibes24** [comment]
I downloaded the xformer file to c drive and did 
pip install c:\xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64

It went without errors. I hope it is right way.

`
(base) C:\Users\vibes24\deforum-stable-diffusion>pip install https://huggingface.co/deforum/xformers/blob/main/windows/xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl
Collecting xformers==0.0.15.dev0fd21b40.d20230107
  Using cached https://huggingface.co/deforum/xformers/blob/main/windows/xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl (38 kB)
ERROR: Wheel 'xformers' located at C:\Users\vibes24\AppData\Local\Temp\pip-unpack-akvqg786\xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl is invalid.

(base) C:\Users\vibes24\deforum-stable-diffusion>pip install c:\xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl
Processing c:\xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl
Requirement already satisfied: torch>=1.12 in c:\users\vibes24\anaconda3\lib\site-packages (from xformers==0.0.15.dev0fd21b40.d20230107) (2.0.0+cu117)
Requirement already satisfied: numpy in c:\users\vibes24\anaconda3\lib\site-packages (from xformers==0.0.15.dev0fd21b40.d20230107) (1.23.5)
Collecting pyre-extensions==0.0.23
  Downloading pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
Requirement already satisfied: typing-extensions in c:\users\vibes24\anaconda3\lib\site-packages (from pyre-extensions==0.0.23->xformers==0.0.15.dev0fd21b40.d20230107) (4.4.0)
Collecting typing-inspect
  Downloading typing_inspect-0.8.0-py3-none-any.whl (8.7 kB)
Requirement already satisfied: filelock in c:\users\vibes24\anaconda3\lib\site-packages (from torch>=1.12->xformers==0.0.15.dev0fd21b40.d20230107) (3.9.0)
Requirement already satisfied: sympy in c:\users\vibes24\anaconda3\lib\site-packages (from torch>=1.12->xformers==0.0.15.dev0fd21b40.d20230107) (1.11.1)
Requirement already satisfied: jinja2 in c:\users\vibes24\anaconda3\lib\site-packages (from torch>=1.12->xformers==0.0.15.dev0fd21b40.d20230107) (3.1.2)
Requirement already satisfied: networkx in c:\users\vibes24\anaconda3\lib\site-packages (from torch>=1.12->xformers==0.0.15.dev0fd21b40.d20230107) (2.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vibes24\anaconda3\lib\site-packages (from jinja2->torch>=1.12->xformers==0.0.15.dev0fd21b40.d20230107) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in c:\users\vibes24\anaconda3\lib\site-packages (from sympy->torch>=1.12->xformers==0.0.15.dev0fd21b40.d20230107) (1.2.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\vibes24\anaconda3\lib\site-packages (from typing-inspect->pyre-extensions==0.0.23->xformers==0.0.15.dev0fd21b40.d20230107) (0.4.3)
Installing collected packages: typing-inspect, pyre-extensions, xformers
Successfully installed pyre-extensions-0.0.23 typing-inspect-0.8.0 xformers-0.0.15.dev0+fd21b40.d20230107

(base) C:\Users\vibes24\deforum-stable-diffusion>
`

**Comment by boxabirds** [comment]
So I'm experimenting with a refreshed install script. AFAICT there are many platform-specific dependencies than there used to be. 

I tried going with just a `requirements.txt` file but because `torch` has index-specific installation instructions no one can specify a `torch` dependency in `requirements.txt` in a platform-independent way. 

But I got the `Deforum_Stable_Diffusion.py` working properly with a plain old `requirements.txt` file plus a manual install of `torch` using the same approach with the extra index url to go to `cu117`. 

This implies the `install_dependencies.py` can be greatly simplified.

**Comment by vibes24** [comment]
> So I'm experimenting with a refreshed install script. AFAICT there are many platform-specific dependencies than there used to be.
> 
> I tried going with just a `requirements.txt` file but because `torch` has index-specific installation instructions no one can specify a `torch` dependency in `requirements.txt` in a platform-independent way.
> 
> But I got the `Deforum_Stable_Diffusion.py` working properly with a plain old `requirements.txt` file plus a manual install of `torch` using the same approach with the extra index url to go to `cu117`.
> 
> This implies the `install_dependencies.py` can be greatly simplified.

You lost me. Hopefully this can be fixed. And hopefully what I did is appropriate and would not break anything.

**Comment by vibes24** [comment]
Unfortunately. I am stuck with new error code.

`
RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?
`

could you provide instructions how to use requirements.txt? Install in DSD or Base (on anaconda)?

**Comment by Gregory667** [comment]
It's similar in my case. During installation, the script does not find the xformers*.whl file in the temp directory. (the file is actually not there).
I then downloaded the file manually and modified 'install_dependencies.py'.
`  windows_xformers = [
        "E:/tools/xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl",
    ]`
That worked for the installation.

But if i activate "dsd" and try to launch the script "Deforum_Stable_Diffusion.py" it says on "..loading model":
"Could not find module 'E:\Programme\anaconda3\envs\dsd\Lib\site-packages\xformers\_C.pyd"

But the file exists.

What can I do to get the software working?

**Comment by boxabirds** [comment]
Until my pull request is accepted use my fork — Windows install works at
least on my Win11 setup

https://github.com/boxabirds/deforum-stable-diffusion

**Comment by Gregory667** [comment]
> Until my pull request is accepted use my fork — Windows install works at least on my Win11 setup https://github.com/boxabirds/deforum-stable-diffusion

Thank you for your help.

The installation has now worked, but I had to install the following packages manually:
ipython
matplotlib

Images are now generated, but with error/warning:

- This warning appears every time: 
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'

- This error appears when I try to create a series of images: 
File "E:\programme\deforum-stable-diffusion\helpers\colors.py", line 15, in maintain_colors
    matched_lab = match_histograms(prev_img_lab, color_match_lab, multichannel=True)
  File "E:\Programme\anaconda3\envs\dsd\lib\site-packages\skimage\_shared\utils.py", line 326, in fixed_func
    return func(*args, **kwargs)
TypeError: match_histograms() got an unexpected keyword argument 'multichannel'

**Comment by boxabirds** [comment]
Ta. Really helpful feedback thank you.

I’m curious why the non-ipynb use case needs those libraries? Happy to put
them back in for now

**Comment by boxabirds** [comment]
Very happy to help. I’ve been thinking about a new disco animation
parameter too — “curve()” that creates a growth or decay curve over a
specified number of frames and a specified rate. By default it’d be
exponential.

**Comment by deforum** [comment]
are you on discord?

**Comment by boxabirds** [comment]
Yep as Julian

**Comment by deforum** [comment]
should be fixed
