### ISSUE TITLE
It would be nice if you specified that this was for windows only -- I can't download the NVIDIA drivers on my mac

### ISSUE THREAD

**Issue by keanedwards1** [deforum-art/deforum-stable-diffusion#200]
It would be nice if you specified that this was for windows only -- I can't download the NVIDIA drivers on my mac.

I'm not an expert in all this, so I'm not sure if there's a way around, but it's just annoying to start something only to find out I can't finish it.

**Comment by Vendaciousness** [comment]
I know people that use Deforum on Mac. You just haven't done your homework. Here's a link I found with a 30 second search on Google:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Installation-on-Apple-Silicon

Please close your issue, so the devs can work on actual problems.

**Comment by keanedwards1** [comment]
me having this issue here doesn't make it so the devs can't work on actual problems -- and thank you. I still think it would be a good thing to include at the top of the readme.

**Comment by giongto35** [comment]
@Vendaciousness it's setup on another repo. We can use deforum on Mac but some people don't want to use WebUI. 
@keanedwards1 your request is valid indeed and I think Dev should take a look on it. A lot of users can just drop interest if they face issue when running the first time.

**Comment by Vendaciousness** [comment]
> @Vendaciousness it's setup on another repo. We can use deforum on Mac but some people don't want to use WebUI. @keanedwards1 your request is valid indeed and I think Dev should take a look on it. I recommend to reopen the ticket. A lot of users can just drop interest if they face issue when running the first time.

His request is NOT valid. It would be valid if the software was designed to support Mac computers, but as it stands, it is not and this can only be done as a hack. You can't expect Microsoft to give you support for Windows 10, if you're running it on an Mac M1, whether or not you manage to get it to run. The software simply isn't programmed for it. There are other repos for that. This repo is for Windows and Linux.
