### ISSUE TITLE
Torch version conflicts during install in WSL

### ISSUE THREAD

**Issue by crowbait** [deforum-art/deforum-stable-diffusion#202]
Tried to install in Windows Subsystem for Linux (Ubuntu in WSL2).

Following error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
```

Tried changing install_requirements.py to include `torch==2.0.0` instead of the default `torch`, but then dependencies installation failed with
```
..installing torch==2.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.16rc424 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
..installing torchvision

...

..installing triton==2.0.0.dev20221202
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
..installing xformers==0.0.16rc424
```
Especially the last bit is weird, since apparently I have both versions now ..?

**Comment by hithereai** [comment]
Just use this instead: https://github.com/deforum-art/deforum-for-automatic1111-webui

On straight windows.

**Comment by crowbait** [comment]
That's what I settled for eventually but I wanted to get it working from scratch.
Anyhow, with the conflict being present, I'd guess something is broken anyway, that's why I opened the issue in the first place. If you're certain everything's fine and it's just a Windows/WSL thing, I'm fine with you closing the ticket.
Just wanted you to know about that (potential) issue.

**Comment by deforum** [comment]
The issue should be resolved by removing the xformers version.
