### ISSUE TITLE
Input type (float) and bias type (struct c10::Half) should be the same

### ISSUE THREAD

**Issue by mohammadmi19** [deforum-art/deforum-stable-diffusion#203]
Error: 'Input type (float) and bias type (struct c10::Half) should be the same'. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \. Full error message is in your terminal/ cli.
how I can fix this?
win11
GTX 1660Ti
Python3.10.6
Already tried --lowvram --no-half I tried everything, 
the problem is when I set keyframes to 3D...
![Screenshot 2023-05-04 000243](https://user-images.githubusercontent.com/67549294/236059844-5b6f2e9e-fe16-4cce-ac7b-575e0914bb96.png)

**Comment by NancyReagan** [comment]
I am having the same problem.

**Comment by deforum** [comment]
please report your issue on https://github.com/deforum-art/sd-webui-deforum/issues

**Comment by gowrimanalan** [comment]
i have the same problem

**Comment by Robotosuza** [comment]
can you help how to solve this error

**Comment by Inflamery** [comment]
same

**Comment by Inflamery** [comment]
![Screenshot_20231025_220256_Chrome](https://github.com/deforum-art/deforum-stable-diffusion/assets/148918801/180cd3f7-fa04-478c-a065-151f60b636e3)
How to fix this? Using CPU instead of GPU?
