### ISSUE TITLE
Deforum Error

### ISSUE THREAD

**Issue by usaid7** [deforum-art/deforum-stable-diffusion#205]
Error: ''DepthModel' object has no attribute 'should_delete''. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \. Full error message is in your terminal/ cli.

**Comment by Linzaer** [comment]
same problem

**Comment by Manish8520** [comment]
Error: ''DepthModel' object has no attribute 'should_delete''. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of . Full error message is in your terminal/ cli. plz fix it reply

**Comment by qinguoliang** [comment]
同样问题

**Comment by deforum** [comment]
could you please explain how you are running deforum?

**Comment by Manish8520** [comment]
My graphics card (nvidia t400) 4gb can I run

**Comment by deforum** [comment]
probably not

**Comment by deforum** [comment]
please continue this conversation on discord
