### ISSUE TITLE
Error: ''NoneType' object has no attribute 'min''.

### ISSUE THREAD

**Issue by nabzahsan** [deforum-art/deforum-stable-diffusion#206]
Error: ''NoneType' object has no attribute 'min''. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \. Full error message is in your terminal/ cli.

Get this error every time I try to generate a video in 3d mode, the rest of the modes are working fine. someone please help

**Comment by hithereai** [comment]
Wrong repository
