### ISSUE TITLE
Getting this error while generating

### ISSUE THREAD

**Issue by cybertron288** [deforum-art/deforum-stable-diffusion#207]
<img width="1457" alt="Screenshot 2023-05-13 at 3 25 49 AM" src="https://github.com/deforum-art/deforum-stable-diffusion/assets/38292293/de881b62-6143-4ce0-992d-24aeb28f0a6b">

When I try to generate I'm getting this error in terminal. please help

**Comment by deforum** [comment]
this error is related to the automatic extension, please create an issue at https://github.com/deforum-art/sd-webui-deforum/issues
