### ISSUE TITLE
Error: ''DepthModel' object has no attribute 'should_delete''. 

### ISSUE THREAD

**Issue by yxriyin** [deforum-art/deforum-stable-diffusion#214]
Error: ''DepthModel' object has no attribute 'should_delete''. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \. Full error message is in your terminal/ cli.

Uncheck Use depth warping can slove the problem, but I need check it.
Who know why?

**Comment by hithereai** [comment]
Wrong repo.
