### ISSUE TITLE
Error:  There is no active internet connection available

### ISSUE THREAD

**Issue by bergkamp** [deforum-art/deforum-stable-diffusion#215]
When I try to use **Enable guided images mode** , got this Exception:

> Error: 'There is no active internet connection available - please use local masks and init files only.'. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \. Full error message is in your terminal/ cli.

This is the default **Images to use for keyframe guidance**

```
{
    "0": "https://deforum.github.io/a1/Gi1.png",
    "max_f/4-5": "https://deforum.github.io/a1/Gi2.png",
    "max_f/2-10": "https://deforum.github.io/a1/Gi3.png",
    "3*max_f/4-15": "https://deforum.github.io/a1/Gi4.jpg",
    "max_f-20": "https://deforum.github.io/a1/Gi1.png"
}
```

When I upload images to my server, and try to use local path , it worked.

**Comment by hithereai** [comment]
Wrong repo.
