### ISSUE TITLE
TypeError: render_animation() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by Uemuet** [deforum-art/deforum-stable-diffusion#221]
there is a new issue when you try to generate something on the Dev version

TypeError: render_animation() takes 4 positional arguments but 5 were given

i hope someone can fix it

**Comment by deforum** [comment]
fixed

**Comment by lanyan520** [comment]
> fixed

Error: render_animation() takes 7 positional arguments but 8 were given

I'd like to know how it was repaired, please
