### ISSUE TITLE
Deforum not working in runpod

### ISSUE THREAD

**Issue by magicgearco** [deforum-art/deforum-stable-diffusion#235]
I move to runpod after stable diffusion not working in google collab, but now in runpod also it's not working. Runpod said that "deforum extension has somehow broken automatic1111 in your case, this part of the issue isn't from our side unfortunately, and I believe you'll have to use atuomatic1111 without deform, or have a codesetup yourself"
So how can I fix this?

**Comment by hithereai** [comment]
Wong repository
