### ISSUE TITLE
[Bug]: Upscale not working on stable diffusion webui colab

### ISSUE THREAD

**Issue by clover0319** [deforum-art/deforum-stable-diffusion#236]
When I use the deforum plugin for stable diffusion webui on Google colab, I select upscale, realesrgan-x4plus-anime, *4 in output, and I get an error every time. The following is the error log.
Got a request to stitch frames to video using FFmpeg.
Frames:
/content/stable-diffusion-webui/outputs/img2img-images/Deforum_20230528002601/20230528002601_%09d.png
To Video:
/content/stable-diffusion-webui/outputs/img2img-images/Deforum_20230528002601/20230528002601.mp4
Stitching *video*...
Video stitching done in 7.31 seconds!
Downloading: "https://github.com/hithereai/Real-ESRGAN/releases/download/real-esrgan-ncnn-linux/realesrgan-ncnn-linux.zip" to /content/stable-diffusion-webui/models/Deforum/realesrgan_ncnn/realesrgan-ncnn-linux.zip

100% 44.2M/44.2M [00:00<00:00, 60.2MB/s]
Upscaling raw output PNGs using realesrgan-x4plus-anime at x4...Error completing request
Arguments: ('task(cj8wkm2wrcrrj9g)', None, False, None, '2D', 60, 'replicate', '0: (0)', '0: (1.0025+0.002*sin(1.25*3.14*t/30))', '0: (0)', '0: (0)', '0: (1.75)', '0: (0.5)', '0: (0.5)', '0: (0)', '0: (0)', '0: (0)', False, '0: (0)', '0: (0)', '0: (0)', '0: (53)', '0: (0.065)', '0: (0.65)', '0: (1.0)', '0: (7)', False, '0: (25)', '0: (70)', '0: (1)', False, '0: (200)', '0: (10000)', '0:(s), 1:(-1), "max_f-2":(-1), "max_f-1":(s)', '0:(1.5)', False, '0: (1)', '0: (0)', False, '0: ("Euler a")', False, '0: ("{video_mask}")', '0: ("{video_mask}")', False, '0: ("model1.ckpt"), 100: ("model2.safetensors")', False, '0: (2)', True, '0: (1.05)', False, '20230129210106', False, '0: (0)', False, '0: (1)', '0: (0.1)', '0: (5)', '0: (1)', '0: (0)', 'LAB', '', 1, False, False, 2, 'None', '0: (1)', 'None', '0: (1)', '0', 'perlin', 8, 8, 4, 0.5, True, 'Midas-3-Hybrid', 0.2, 'border', 'bicubic', False, 'https://deforum.github.io/a1/V1.mp4', 1, 0, -1, False, False, 'https://deforum.github.io/a1/VM1.mp4', '0:(0.5)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', '0:(1)', False, 'None', True, 'None', False, False, 2, 'RAFT', 'None', False, 'None', False, 'None', False, False, '{\n    "0": "tiny cute swamp bunny, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera",\n    "30": "anthropomorphic clean cat, surrounded by fractals, epic angle and pose, symmetrical, 3d, depth of field, ruan jia and fenghua zhong"\n}\n    ', '', 'nsfw, nude', 512, 512, True, False, False, 0, 0, -1, 'Euler a', 25, 'Deforum_{timestring}', 'iter', 1, False, 0.8, True, 'https://deforum.github.io/a1/I1.png', False, False, 'https://deforum.github.io/a1/M1.jpg', False, 1.0, 1.0, True, 4, 'fill', True, 4, 'ignore', 10.0, False, 15, False, False, 'C:/SD/20230124234916_%09d.png', 'None', 'https://deforum.github.io/a1/A1.mp3', True, 'x4', 'realesrgan-x4plus-anime', True, False, 'None', 2, False, 2, False, '', True, False, '{\n    "0": "https://deforum.github.io/a1/Gi1.png",\n    "max_f/4-5": "https://deforum.github.io/a1/Gi2.png",\n    "max_f/2-10": "https://deforum.github.io/a1/Gi3.png",\n    "3*max_f/4-15": "https://deforum.github.io/a1/Gi4.jpg",\n    "max_f-20": "https://deforum.github.io/a1/Gi1.png"\n}', '0:(0.75)', '0:(0.35)', '0:(0.25)', '0:(20)', '0:(0.075)', True, '', '', False, False, False, 'none', 'None', '0:(1)', '0:(0.0)', '0:(1.0)', 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', False, True, '', '', False, False, False, 'none', 'None', '0:(1)', '0:(0.0)', '0:(1.0)', 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', False, True, '', '', False, False, False, 'none', 'None', '0:(1)', '0:(0.0)', '0:(1.0)', 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', False, True, '', '', False, False, False, 'none', 'None', '0:(1)', '0:(0.0)', '0:(1.0)', 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', False, True, '', '', False, False, False, 'none', 'None', '0:(1)', '0:(0.0)', '0:(1.0)', 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', False) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/run_deforum.py", line 155, in run_deforum
    make_upscale_v2(upscale_factor = video_args.r_upscale_factor, upscale_model = video_args.r_upscale_model, keep_imgs = video_args.r_upscale_keep_imgs, imgs_raw_path = args.outdir, imgs_batch_id = root.timestring, fps = video_args.fps, deforum_models_path = root.models_path, current_user_os = root.current_user_os, ffmpeg_location=f_location, stitch_from_frame=0, stitch_to_frame=max_video_frames, ffmpeg_crf=f_crf, ffmpeg_preset=f_preset, add_soundtrack = video_args.add_soundtrack ,audio_path=real_audio_track, srt_path=srt_path)
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/upscaling.py", line 143, in make_upscale_v2
    process = subprocess.run(cmd, capture_output=True, check=True, text=True, cwd=(os.path.join(deforum_models_path, 'realesrgan_ncnn') if current_user_os == 'Mac' else None))
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/content/stable-diffusion-webui/models/Deforum/realesrgan_ncnn/realesrgan-ncnn-vulkan', '-i', '/content/stable-diffusion-webui/outputs/img2img-images/Deforum_20230528002601/20230528002601_upscaled/temp_raw_imgs_to_upscale', '-o', '/content/stable-diffusion-webui/outputs/img2img-images/Deforum_20230528002601/20230528002601_upscaled', '-s', '4', '-n', 'realesrgan-x4plus-anime']' returned non-zero exit status 255.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

**Comment by deforum** [comment]
please use https://github.com/deforum-art/sd-webui-deforum/issues to report this issue
