### ISSUE TITLE
Confused on the code structure

### ISSUE THREAD

**Issue by MaxTran96** [deforum-art/deforum-stable-diffusion#238]
Hello, what's the difference between this Predictor class https://github.com/deforum-art/deforum-stable-diffusion/blob/main/predict.py

and 

https://github.com/deforum-art/deforum-stable-diffusion/blob/main/Deforum_Stable_Diffusion.py

I'm relatively new to Deforum

**Comment by deforum** [comment]
the predict is used by replicate https://replicate.com/deforum-art/deforum-stable-diffusion
