### ISSUE TITLE
non-ziro

### ISSUE THREAD

**Issue by sowabcd** [deforum-art/deforum-stable-diffusion#239]
Wanted outputs:
    [gallery, textbox, textbox, html]
Received outputs:
    [None, "", "<div class='error'>CalledProcessError: Command &#x27;[&#x27;J:\\Administrator\\miaoshouai-sd-webui-v230222full\\models/Deforum\\realesrgan_ncnn\\realesrgan-ncnn-vulkan.exe&#x27;, &#x27;-i&#x27;, &#x27;J:\\Administrator\\miaoshouai-sd-webui-v230222full\\outputs/img2img-images\\3D-Vedio-20230530204928\\20230530204928_upscaled\\temp_raw_imgs_to_upscale&#x27;, &#x27;-o&#x27;, &#x27;J:\\Administrator\\miaoshouai-sd-webui-v230222full\\outputs/img2img-images\\3D-Vedio-20230530204928\\20230530204928_upscaled&#x27;, &#x27;-s&#x27;, &#x27;-1&#x27;, &#x27;-n&#x27;, &#x27;realesr-animevideov3&#x27;]&#x27; returned non-zero exit status 3221226505.</div><div class='performance'><p class='time'>Time taken: <wbr>1m 55.90s</p><p class='vram'>Torch active/reserved: 5110/5408 MiB, <wbr>Sys VRAM: 7764/12282 MiB (63.21%)</p></div>"]
![捕获](https://github.com/deforum-art/deforum-stable-diffusion/assets/87592693/774d4ebb-2b83-4eec-b26d-e2b117bed3a9)

**Comment by deforum** [comment]
please use https://github.com/deforum-art/sd-webui-deforum/issues for this issue
