### ISSUE TITLE
Google colab: Non-zero exit status 128

### ISSUE THREAD

**Issue by Knitterpower** [deforum-art/deforum-stable-diffusion#241]
Hello, 

I try to run the deforum-stable-diffusion on google colab. While running the environment setup, I get an error message, particularly at that point:

# Cloning the github repository
        subprocess.check_call(['git', 'clone', 'https://github.com/deforum-art/deforum-stable-diffusion'])

This is the error message: 

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-9-1446cba4479c>](https://67yr0wqnk2m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230526-060153-RC00_535578354#) in <cell line: 55>()
     53         print("..skipping setup")
     54 
---> 55 setup_environment()
     56 
     57 import torch

1 frames
[/usr/lib/python3.10/subprocess.py](https://67yr0wqnk2m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230526-060153-RC00_535578354#) in check_call(*popenargs, **kwargs)
    367         if cmd is None:
    368             cmd = popenargs[0]
--> 369         raise CalledProcessError(retcode, cmd)
    370     return 0
    371 

CalledProcessError: Command '['git', 'clone', 'https://github.com/deforum-art/deforum-stable-diffusion']' returned non-zero exit status 128.

Does someone know what I'm doing wrong? 

Thanks and best
Niklas

**Comment by deforum** [comment]
fixed
