### ISSUE TITLE
Finished Creation Without Results

### ISSUE THREAD

**Issue by Kupicki** [deforum-art/deforum-stable-diffusion#249]
I put an image to generate the sequence, adjusted some settings and left the default prompt to see how the result would look. After 3 hours of waiting and processing, the file was apparently finished, I clicked to show the video and nothing, just a black screen. I went to the output folder directory, where apparently my files should be, or at least the PNG files and nothing, just a settings document...

What could have happened? Could the files have ended up in another folder?
P.S: No error message during the whole process. The folder where I went looking for the file, following the indication of other users is C:\Users\...\A1111 Web UI AutoInstaller\stable-diffusion-webui\outputs\img2img-images

**Comment by deforum** [comment]
you are looking for https://github.com/deforum-art/sd-webui-deforum
