### ISSUE TITLE
Controlnet not applying to output 

### ISSUE THREAD

**Issue by digitallemming** [deforum-art/deforum-stable-diffusion#256]
I'm familiar with Deforum and Controlnet and I can't seem to get Controlnet to apply to the outputs. When I check the output folder it has successfully separated each frame from the input vid however it is not applied to the frames it produces. 

I'm just doing a 2D video, the path is linked correctly, the cadence is not too high, there's no motion or anything. I'm using canny and openpose face for controlnet, they are both enabled and set to "controlnet is more important". I do not have any issues applying controlnet anywhere else in A1111. I've been trying stuff all day and can't seem to get it too apply at all.

**Comment by deforum** [comment]
please submit this issue to https://github.com/deforum-art/sd-webui-deforum
