### ISSUE TITLE
 'triton xformers==0.0.21.dev542'

### ISSUE THREAD

**Issue by hipnotrip** [deforum-art/deforum-stable-diffusion#263]
I can't execute environnement setup this morning : 
..installing triton xformers==0.0.21.dev542
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-4-dfc48511d2f3>](https://localhost:8080/#) in <cell line: 35>()
     33         print("..skipping setup")
     34 
---> 35 setup_environment()
     36 
     37 import torch

1 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in check_call(*popenargs, **kwargs)
    367         if cmd is None:
    368             cmd = popenargs[0]
--> 369         raise CalledProcessError(retcode, cmd)
    370     return 0
    371 

CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'triton', 'xformers==0.0.21.dev542']' returned non-zero exit status 1.

**Comment by Danefron** [comment]
I have same error 😕

**Comment by Danefron** [comment]
![Screenshot_20230610-105535](https://github.com/deforum-art/deforum-stable-diffusion/assets/86188096/3af4b5ed-b266-4743-826d-38a89e2e3103)

**Comment by hipnotrip** [comment]
Found !! 
Try to modify : **triton xformers==0.0.21.dev542** by **triton xformers==0.0.21.dev546**
 
 Like this :
 if 'google.colab' in str(ipy):
        start_time = time.time()
        packages = [
            'triton xformers==0.0.21.dev546',

**Comment by SandrewArt** [comment]
> Found !! Try to modify : **triton xformers==0.0.21.dev542** by **triton xformers==0.0.21.dev546**
> 
> Like this : if 'google.colab' in str(ipy): start_time = time.time() packages = [ 'triton xformers==0.0.21.dev546',

it work for me

**Comment by maykkon5** [comment]
I had the same problem, and after doing what was suggested the problem was fixed!!

thanks!!

**Comment by deforum** [comment]
i just updated the xformers version in main
