### ISSUE TITLE
colaboratory CalledProcess Error issue 

### ISSUE THREAD

**Issue by thc7650** [deforum-art/deforum-stable-diffusion#264]
..installing triton xformers==0.0.21.dev542
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-6-a7d747fc67e4>](https://5fguahv4u36-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230608-060129-RC01_538830856#) in <cell line: 32>()
     30         print("..skipping setup")
     31 
---> 32 setup_environment()
     33 
     34 import torch

1 frames
[/usr/lib/python3.10/subprocess.py](https://5fguahv4u36-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230608-060129-RC01_538830856#) in check_call(*popenargs, **kwargs)
    367         if cmd is None:
    368             cmd = popenargs[0]
--> 369         raise CalledProcessError(retcode, cmd)
    370     return 0
    371 

CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'triton', 'xformers==0.0.21.dev542']' returned non-zero exit status 1.

                                            PLEASE  HELP !!!
#it to much called for server - WHAT NOW WE MUST TO DO ???

**Comment by alexwasner** [comment]
https://github.com/deforum-art/deforum-stable-diffusion/issues/263#issuecomment-1585501871

**Comment by deforum** [comment]
fixed
