### ISSUE TITLE
Environment Setup error

### ISSUE THREAD

**Issue by Dyaastar** [deforum-art/deforum-stable-diffusion#265]
Environment Setup

..installing triton xformers==0.0.21.dev542
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-2-dfc48511d2f3>](https://localhost:8080/#) in <cell line: 35>()
     33         print("..skipping setup")
     34 
---> 35 setup_environment()
     36 
     37 import torch

1 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in check_call(*popenargs, **kwargs)
    367         if cmd is None:
    368             cmd = popenargs[0]
--> 369         raise CalledProcessError(retcode, cmd)
    370     return 0
    371 

CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'triton', 'xformers==0.0.21.dev542']' returned non-zero exit status 1.

**Comment by alexwasner** [comment]
https://github.com/deforum-art/deforum-stable-diffusion/issues/263#issuecomment-1585501871

**Comment by Dyaastar** [comment]
it is good now after the update

**Comment by Dyaastar** [comment]
it is good now after the update
