### ISSUE TITLE
Feature request: "Live" mode

### ISSUE THREAD

**Issue by Gwynei** [deforum-art/deforum-stable-diffusion#275]
Pretty often I'm generating and watching the progress, and I'm thinking, no no no, this is going the wrong way. But I can't change it as the prompts and settings are set first.

What if there was a live mode implemented, where you can alter the prompt while it's generating? Basically instead of reading the prompt tab once, it should re-read the prompt tab and all the other settings during every generation when live mode is enabled.

Imagine the possibilites...

**Comment by deforum** [comment]
you can always end the generation and continue with new prompts and settings
