### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by marius-jopen** [deforum-art/deforum-stable-diffusion#293]
Hello dear Deforum team 
I just got banned from the discord server because I posted some videos I made. The videos are a mix of food and porn. I see this as an artistic experiment and didn't not want to offend anyone. 
I now understand that you don't want this to be visible on your discord server. And will not post it again - if you let me back in. 

I very much enjoy working with Deforum and value the community around it. 

So no more borderline posts from me. Promise 🙏

**Comment by deforum** [comment]
what is your discord account again? ill add you back

**Comment by marius-jopen** [comment]
😄 Thank you!!
It is: mariusjopen

🙏

**Comment by deforum** [comment]
you need to accept my friend request

**Comment by marius-jopen** [comment]
Done! Thank you! :-D

**Comment by Vendaciousness** [comment]
You should close this issue, @marius-jopen
