### ISSUE TITLE
xformers==0.0.21.dev568 is throwing errors

### ISSUE THREAD

**Issue by noveck** [deforum-art/deforum-stable-diffusion#297]
Fix is to update to xformers==0.0.21.dev569 in the setup section

if 'google.colab' in str(ipy):
        start_time = time.time()
        packages = [
         **'triton xformers==0.0.21.dev569',**
            'einops==0.4.1 pytorch-lightning==1.7.7 torchdiffeq==0.2.3 torchsde==0.2.5',
            'ftfy timm transformers open-clip-torch omegaconf torchmetrics==0.11.4',
            'safetensors kornia accelerate jsonmerge matplotlib resize-right',
            'scikit-learn numpngw pydantic'

**Comment by DevduttoKanungo** [comment]
You are a life saver
