### ISSUE TITLE
python Deforum_Stable_Diffusion.py gives error re triton version; python 3.10.8

### ISSUE THREAD

**Issue by RightSexyOrc** [deforum-art/deforum-stable-diffusion#30]
python Deforum_Stable_Diffusion.py
NVIDIA GeForce RTX 3060, 12288 MiB, 10153 MiB
..installing xformers
ERROR: Could not find a version that satisfies the requirement triton==2.0.0.dev20220701 (from versions: 2.0.0.dev20221030, 2.0.0.dev20221031, 2.0.0.dev20221101, 2.0.0.dev20221103, 2.0.0.dev20221105)
ERROR: No matching distribution found for triton==2.0.0.dev20220701
NVIDIA GeForce RTX 3060
 is currently not supported with xformers flash attention in deforum!

Deforum_Stable_Diffusion.py", line 91, in setup_environment
    x_link = 'https://github.com/TheLastBen/fast-stable-diffusion/raw/main/precompiled/' + name_to_download + '/' + x_ver
UnboundLocalError: local variable 'name_to_download' referenced before assignment

thanks!

**Comment by RightSexyOrc** [comment]
pip install triton==2.0.0.dev20220701
ERROR: Could not find a version that satisfies the requirement triton==2.0.0.dev20220701 (from versions: 2.0.0.dev20221030, 2.0.0.dev20221031, 2.0.0.dev20221101, 2.0.0.dev20221103, 2.0.0.dev20221105)
ERROR: No matching distribution found for triton==2.0.0.dev20220701

**Comment by RightSexyOrc** [comment]
pip install triton==2.0.0.dev20221105
Collecting triton==2.0.0.dev20221105

installed...

python Deforum_Stable_Diffusion.py
NVIDIA GeForce RTX 3060, 12288 MiB, 9913 MiB
..installing xformers
NVIDIA GeForce RTX 3060
 is currently not supported with xformers flash attention in deforum!
Traceback (most recent call last):
  File "...deforum-stable-diffusion/Deforum_Stable_Diffusion.py", line 112, in <module>
    setup_environment()
  File "...deforum-stable-diffusion/Deforum_Stable_Diffusion.py", line 91, in setup_environment
    x_link = 'https://github.com/TheLastBen/fast-stable-diffusion/raw/main/precompiled/' + name_to_download + '/' + x_ver
UnboundLocalError: local variable 'name_to_download' referenced before assignment

**Comment by deforum** [comment]
looks like you are modifying the run script do download xformers. for local installations you should not do this. for local installations you should be installing xformers from source for your specific gpu.
