### ISSUE TITLE
Environment Setup not working deforum

### ISSUE THREAD

**Issue by Jayrahx** [deforum-art/deforum-stable-diffusion#302]
Environment Setup not working deforum

..installing triton xformers==0.0.21.dev569
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-2-cd22dc4ec95d>](https://localhost:8080/#) in <cell line: 35>()
     33         print("..skipping setup")
     34 
---> 35 setup_environment()
     36 
     37 import torch

1 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in check_call(*popenargs, **kwargs)
    367         if cmd is None:
    368             cmd = popenargs[0]
--> 369         raise CalledProcessError(retcode, cmd)
    370     return 0
    371 

CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'triton', 'xformers==0.0.21.dev569']' returned non-zero exit status 1.

**Comment by welcometothesmittiverse** [comment]
I have the same problem. Also path setup is not working after...

**Comment by ceotechiq** [comment]
Here's a trick I used to fix this the last four times it's happened. 

in a cell type
!pip install xformers==1010
You'll get back a list of valid distriubtions.  0.0.21.dev571, 0.0.21.dev572, 0.0.21.dev573, 0.0.21.dev574, 0.0.21.dev575 will fix this error, but you'll run into another one that I logged a ticket for.

ERROR: Could not find a version that satisfies the requirement xformers==1010 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21.dev571, 0.0.21.dev572, 0.0.21.dev573, 0.0.21.dev574, 0.0.21.dev575)

**Comment by ceotechiq** [comment]
*****After attempting to use 0.0.21.dev571, 0.0.21.dev572, 0.0.21.dev573, 0.0.21.dev574, 0.0.21.dev575  keep getting an error that says "RuntimeError: FlashAttention only supports Ampere GPUs or newer."

I fixed this by using the last stable version triton xformers==0.0.20

Please follow me on threads ai_gangster or twitter @searchFantasy

**Comment by deforum** [comment]
xformers==0.0.21.dev575 fixed in main
