### ISSUE TITLE
Control nets only take as input the first frame.

### ISSUE THREAD

**Issue by ca3gamedev** [deforum-art/deforum-stable-diffusion#311]
Hi, since I make a 3d model to make an animation, I was able to generate on Krita an open pose animation and use Krita and Blender to generate a depth map animation.

So I have a difusse 3D low poly render, a depth map video and an open pose animation of the same animation.
I was unable to get the controlnets to have an effect beyond the first frame of the control nets videos, and as such, my output is just an static video.

I already tried to use .webm, .mp4, .gif and a folder with .png.
Same issue with all.

Since another user on the discord, reported me that he seems to get the same issue, I was able to guess it wasn't because an improper setting on my part.

https://github.com/deforum-art/deforum-stable-diffusion/assets/115381195/3459acdc-bf68-4012-b8dc-c3e206a86ee4

This is how my output looks like.

**Comment by chriskerluke** [comment]
Did you figure this out?

I'm coming to the conclusion that you can't change between control net poses/depths between key frames. Or atleast I can't figure out how

**Comment by ca3gamedev** [comment]
> Did you figure this out?
> 
> I'm coming to the conclusion that you can't change between control net poses/depths between key frames. Or atleast I can't figure out how

Yes, It seems I had to use video mode, instead of 2D mode input.
