### ISSUE TITLE
ControlNet not found. Please install it :)

### ISSUE THREAD

**Issue by nblive15** [deforum-art/deforum-stable-diffusion#323]
Controlnet appears with tabs and works perfectly in text2img and img2img, but in deforum this message appears
"ControlNet not found. Please install it :)"

I'm using controlnet
https://github.com/Mikubill/sd-webui-controlnet
in the most updated version
is installed in the default location
stable-diffusion-webui/extensions/sd-webui-controlnet
I don't use any ad blockers
only the original google chrome in the latest version
I'm using stable diffusion automatic webui
original
https://github.com/AUTOMATIC1111/stable-diffusion-webui

I believe it is an error in the deforum, otherwise it would not works  in the txt2img and img2img
![exten off](https://github.com/deforum-art/deforum-stable-diffusion/assets/133683188/64c7cbb0-cdbc-4270-b5ca-06b61d3c826d)

**Comment by nblive15** [comment]
Wrong repository

**Comment by nblive15** [comment]
Wrong repository

**Comment by nanjingzhouyu** [comment]
same issue, did u find out why this issue?

**Comment by nanjingzhouyu** [comment]
> same issue, did u find out why this issue?

I fixed it, just install the ControlNet from webui Extensions Tab
