### ISSUE TITLE
CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', 'triton', 'xformers==0.0.21.dev581']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by jorgerestifojampp** [deforum-art/deforum-stable-diffusion#325]
anyone having this issue?

**Comment by glancione** [comment]
I have the same problem :(

**Comment by glancione** [comment]
i changed 
'triton xformers==0.0.21.dev581'

with

triton xformers==0.0.21.dev590

and now it works 

Hope it works also for you :D 
Bye

**Comment by glancione** [comment]
> anyone having this issue?

i changed 

'triton xformers==0.0.21.dev581'

with 

'triton xformers==0.0.21.dev590'

now it works fine. Let me know if it works also for you :D 

bye

**Comment by jorgerestifojampp** [comment]
worked for me, thanks!
