### ISSUE TITLE
API info?

### ISSUE THREAD

**Issue by F0xbite** [deforum-art/deforum-stable-diffusion#330]
Any info on how to use Deforum through the Automatic1111 API? Thanks in advance.

**Comment by juanctecdam** [comment]
Same question here! Any information?

**Comment by Vance-Xu** [comment]
same question !!

**Comment by bodssfh** [comment]
Hello world 
API Logen info

**Comment by GrigorySamokhin** [comment]
Hello @F0xbite! How did you solve it?
