### ISSUE TITLE
DeforumStableDiffusion RuntimeError colab

### ISSUE THREAD

**Issue by Domqwerty** [deforum-art/deforum-stable-diffusion#346]
DeforumStableDiffusion reports me an error : RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA major versions. PyTorch has CUDA Version=12.1 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install

**Comment by deforum** [comment]
fixed

**Comment by Joplin399** [comment]
Hi, I got the same error. How did you fix it?
Thanks
