### ISSUE TITLE
prompt_weight could not convert string to float error

### ISSUE THREAD

**Issue by AIManifest** [deforum-art/deforum-stable-diffusion#54]
Hey Devs! AMAZING job with the progress in V0.6! Just hitting an error when experimenting with weights, hopefully we can get this resolved. I've tried many syntaxes and many formats for one line of my long list of prompts, but I just can't seem to get them to work. Any assistance will be amazing. Thanks in advance!

ValueError                                Traceback (most recent call last)

[<ipython-input-78-2fb4847935d1>](https://localhost:8080/#) in <module>
    150 # dispatch to appropriate renderer
    151 if anim_args.animation_mode == '2D' or anim_args.animation_mode == '3D':
--> 152     render_animation(args, anim_args, animation_prompts, root)
    153 
    154 elif anim_args.animation_mode == 'Video Input':

4 frames

[/content/deforum-stable-diffusion/helpers/render.py](https://localhost:8080/#) in render_animation(args, anim_args, animation_prompts, root)
    304                 args.mask_file = mask_frame
    305 
--> 306         # sample the diffusion model
    307         sample, image = generate(args, root, frame_idx, return_latent=False, return_sample=True)
    308         # First image sample used for masking

[/content/deforum-stable-diffusion/helpers/generate.py](https://localhost:8080/#) in generate(args, root, frame, return_latent, return_sample, return_c)
    139 
    140     if args.clip_scale != 0:
--> 141         clip_loss_fn = make_clip_loss_fn(root, args)
    142     else:
    143         clip_loss_fn = None

[/content/deforum-stable-diffusion/helpers/conditioning.py](https://localhost:8080/#) in make_clip_loss_fn(root, args)
     72 
     73     make_cutouts = MakeCutouts(clip_size, args.cutn, args.cut_pow)
---> 74     target_embeds, weights = parse_clip_prompts(args.clip_prompt)
     75 
     76     def clip_loss_fn(x, sigma, **kwargs):

[/content/deforum-stable-diffusion/helpers/conditioning.py](https://localhost:8080/#) in parse_clip_prompts(clip_prompt)
     58         target_embeds, weights = [], []
     59         for prompt in clip_prompt:
---> 60             txt, weight = parse_prompt(prompt)
     61             target_embeds.append(root.clip_model.encode_text(clip.tokenize(txt).to(root.device)).float())
     62             weights.append(weight)

[/content/deforum-stable-diffusion/helpers/conditioning.py](https://localhost:8080/#) in parse_prompt(prompt)
     53             vals = prompt.rsplit(':', 1)
     54         vals = vals + ['', '1'][len(vals):]
---> 55         return vals[0], float(vals[1])
     56 
     57     def parse_clip_prompts(clip_prompt):
[20221201064148_settings.txt](https://github.com/deforum-art/deforum-stable-diffusion/files/10129935/20221201064148_settings.txt)

ValueError: could not convert string to float: ''

**Comment by ahmadmustafaanis** [comment]
Any solution you cam across?
