### ISSUE TITLE
Video mask feature makes use of only the first frame

### ISSUE THREAD

**Issue by fritzy3** [deforum-art/deforum-stable-diffusion#58]
Using the same settings and files (init video and video mask) v0.6 behaves differently than v0.5. It doesn't progress the video mask frames (even though they were extracted) and leaves the first video mask frame for the entire duration of the output video.

**Comment by sheneman** [comment]
@fritzy3  - I experienced the same thing.   I was able to confirm that the mask video frames were being read properly in helpers/generate.py, but that the mask from the first frame seems to have a special significance which is either undocumented or it is a bug.   In any event, my workaround was to set the first mask frame to ALL black.   The subsequent mask frames read from the mask video were then honored and everything worked.   I then discarded the first frame of the resulting video.
